import React, { createContext, useState, useEffect, useContext } from 'react';
import { useNavigate } from 'react-router-dom';
import { v4 as uuidv4 } from 'uuid';

// Create the AuthContext
export const AuthContext = createContext(null);

/**
 * Provides authentication state and functions to its children.
 * Manages access token storage, user data, settings, login, and logout.
 */
export const AuthProvider = ({ children }) => {
  // Initialize token and user from localStorage (for persistence across sessions)
  const [token, setToken] = useState(localStorage.getItem('token'));
  const [user, setUser] = useState(null);
  const [loading, setLoading] = useState(true);
  const [settings, setSettings] = useState({});
  const [deviceId, setDeviceId] = useState(localStorage.getItem('deviceId'));
  const navigate = useNavigate();

  // Effect to generate and persist deviceId on first load
  useEffect(() => {
    if (!deviceId) {
      const newDeviceId = uuidv4();
      localStorage.setItem('deviceId', newDeviceId);
      setDeviceId(newDeviceId);
    }
  }, [deviceId]);

  // Function to save token to localStorage
  const saveToken = (newToken) => {
    setToken(newToken);
    if (newToken) {
      localStorage.setItem('token', newToken);
    } else {
      localStorage.removeItem('token');
    }
  };

  // Function to fetch user data using the token
  const fetchUser = async (current_token) => {
    if (!current_token) {
      setUser(null);
      setLoading(false);
      return;
    }
    try {
      const response = await fetch('/api/users/me/', {
        headers: {
          'Authorization': `Bearer ${current_token}`,
        },
      });
      if (response.ok) {
        const userData = await response.json();
        setUser(userData);
      } else {
        // If token is invalid or expired, clear it
        console.error("Failed to fetch user data, token might be invalid or expired.");
        saveToken(null);
        setUser(null);
      }
    } catch (error) {
      console.error("Error fetching user data:", error);
      saveToken(null); // Clear token on network/other errors
      setUser(null);
    } finally {
      //setLoading(false);
    }
  };

  // Function to fetch global/user/device settings
  const fetchSettings = async () => {
    // Only fetch settings if deviceId is available
    if (!deviceId) {
        console.warn("Device ID not available, skipping settings fetch.");
        setLoading(false);
        return;
    }

    try {
      const headers = token ? { 'Authorization': `Bearer ${token}` } : {};
      const response = await fetch(`/api/settings/?device_id=${deviceId}`, {
        headers: headers,
      });
      if (response.ok) {
        const settingsData = await response.json();
        setSettings(settingsData);
      } else {
        console.error("Failed to fetch settings:", response.statusText);
        // If settings fetching fails, provide a fallback or sensible defaults
        setSettings({ sidebar: 'left' });
      }
    } catch (error) {
      console.error("Error fetching settings:", error);
      setSettings({ sidebar: 'left' }); // Fallback on network error
    } finally {
      setLoading(false);
    }
  };

  // Effect to load user data and settings when token or deviceId changes
  useEffect(() => {
    // Only run if deviceId is present (it's generated by its own useEffect)
    if (deviceId) {
      const loadInitialData = async () => {
        setLoading(true);
        // Fetch user first to get current_user.id for settings API if needed
        // (though current /api/settings/ directly takes user from token if present)
        await fetchUser(token);
        await fetchSettings();
      };
      loadInitialData();
    }
  }, [token, deviceId]);

  // Login function
  const login = async (username, password) => {
    const formData = new URLSearchParams();
    formData.append('username', username);
    formData.append('password', password);

    try {
      const response = await fetch('/api/token', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/x-www-form-urlencoded',
        },
        body: formData.toString(),
      });

      if (response.ok) {
        const data = await response.json();
        saveToken(data.access_token);
        // fetchUser will be called by useEffect due to token change
        navigate('/'); // Redirect to home page after successful login
      } else {
        const errorData = await response.json();
        console.error('Login failed:', errorData.detail);
        return { success: false, message: errorData.detail || 'Login failed' };
      }
    } catch (error) {
      console.error('Network error during login:', error);
      return { success: false, message: 'Network error during login' };
    }
    return { success: true };
  };

  // Signup function
  const signup = async (username, password, admin = false, login_allowed = false) => {
    try {
      const response = await fetch('/api/signup/', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ username, password, admin, login_allowed }),
      });

      if (response.ok) {
        // Optionally log in the user immediately after signup
        // await login(username, password);
        return { success: true, message: "Signup successful. You can now log in." };
      } else {
        const errorData = await response.json();
        console.error('Signup failed:', errorData.detail);
        return { success: false, message: errorData.detail || 'Signup failed' };
      }
    } catch (error) {
      console.error('Network error during signup:', error);
      return { success: false, message: 'Network error during signup' };
    }
  };

  // Logout function
  const logout = () => {
    saveToken(null);
    setUser(null);
    navigate('/login'); // Redirect to login page after logout
  };

  const isAdmin = user && user.admin;

  const authContextValue = {
    token,
    user,
    loading,
    isAuthenticated: !!token && !!user, // User is authenticated if token and user data exist
    login,
    signup,
    logout,
    isAdmin,
    settings,
    deviceId,
    fetchSettings,
  };

  return (
    <AuthContext.Provider value={authContextValue}>
      {children}
    </AuthContext.Provider>
  );
};

// Custom hook for easy access to AuthContext
export const useAuth = () => useContext(AuthContext);
